### ISSUE TITLE
DateTime array handling

### ISSUE THREAD

**Issue by innat3** [AlienEngineer/CSMatIO#2]
Hello I need to work with DateTime arrays but so far the only option I see is using the MLCell array, which takes up too much disk space, would it be possible to implement a new array type for storing and reading DateTime values?

**Comment by Rufus31415** [comment]
Hi,
I had the same issue and finally I store the datetime variables with format ole date (double) using the .NET function myDateTime.ToOADate().
In your MATLAB code you can invoke the .NET function that reconverts ole date to DateTime
