### ISSUE TITLE
Are you still maintaining this?

### ISSUE THREAD

**Issue by damageboy** [AlienEngineer/CSMatIO#6]
Hi,
I have my own repo now at:
https://github.com/damageboy/csmatio

The main improvements (?) over your version are:
- [x] Has unit tests
- [x] Has appveyor build

Would you like to take ownership of my changes or alternatively release the nuget push rights to me?

I'd rather not create a superfluous polution in nuget for this package... :)

Any thoughts?

**Comment by AlienEngineer** [comment]
Hi,

I've created this repo only to publish the code as a Lib via NuGet. I can give you access to push.

What's your username on Nuget.org?

**Comment by damageboy** [comment]
I'm @damageboy on nuget.org as well :)

Thanks!

**Comment by damageboy** [comment]
Thanks for everything!
I have now wite perms on the nuget...

I'll push the nupkg later today over there...
